"""join booster

Revision ID: 241029f49b77
Revises: 3fad2cf8ca0f
Create Date: 2024-07-20 23:11:59.832915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241029f49b77'
down_revision: Union[str, None] = '3fad2cf8ca0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_actions_action'), 'actions', ['action'], unique=False)
    op.create_index(op.f('ix_actions_link'), 'actions', ['link'], unique=False)
    op.create_unique_constraint(None, 'bots', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bots', type_='unique')
    op.drop_index(op.f('ix_actions_link'), table_name='actions')
    op.drop_index(op.f('ix_actions_action'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
