"""update model actions

Revision ID: 683f2215110f
Revises: 386b594210ef
Create Date: 2024-07-21 13:12:25.375217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683f2215110f'
down_revision: Union[str, None] = '386b594210ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('type_action', sa.String(), nullable=True))
    op.create_index(op.f('ix_actions_type_action'), 'actions', ['type_action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_type_action'), table_name='actions')
    op.drop_column('actions', 'type_action')
    # ### end Alembic commands ###
